# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


continuation_prompt = '[>>](bold green)'

#right_format = """
#$git_branch\
#"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[lua]
disabled = true

[git_status]
modified = "~"
untracked = ""
staged = ""
deleted = ""
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
format = '([$all_status$ahead_behind]($style))'
style = "yellow"
