## based on https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


bind -n M-r split-window -h
bind -n M-d split-window -v

setw -g xterm-keys on

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-m select-pane -D



# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf


# don't rename windows automatically
set-option -g allow-rename off


setw -g mode-keys vi


# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none


# Catppuccin theme
set -g default-terminal "tmux-256color"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
