## based on https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


bind -n M-r split-window -h
bind -n M-d split-window -v

setw -g xterm-keys on

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-m select-pane -D

bind -n M-q kill-pane
bind -n M-t new-window
bind -n M-, command-prompt -I "#W" "rename-window '%%'"

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5


## dim inactive pane
set-window-option -g window-style fg=white,bg=colour236
set-window-option -g window-active-style fg=white,bg=colour235




# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# cheatsheet popup
bind ? display-popup -E -h 80% -w 60% "less ~/.tmux-cheatsheet"

# lazygit popup
bind-key g display-popup -w 90% -h 90% -E -d '#{pane_current_path}' lazygit


# start window and pane numbering from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# don't rename windows automatically
set-option -g allow-rename off


setw -g mode-keys vi


# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none


# Catppuccin theme
set -g default-terminal "tmux-256color"
set -g status-position top
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_date_time_text "%H:%M"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_date_time}"
set -g status-right-length 100
